### ISSUE TITLE
Accepting paypal for collecting other people's work?

### ISSUE THREAD

**Issue by huachuman** [r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets#1]
That doesn't seem too nice.

**Comment by r-u-s-h-i-k-e-s-h** [comment]
> That doesn't seem too nice.

I understand your concern. Let me provide some clarity:

1. I have obtained permission from the main contributors _kneecaps, sailKite, and FireIsGood_. They are fully supportive of this project. Additionally, I've included a '**Buy me a Coffee'** link for _kepano and Anubis's_ snippets.
2. I invested significant time in collecting and organizing these snippets.
3. The entire repository is offered for free use by everyone.
4. Proper credit is given to each contributor in their respective snippet files.

I appreciate your feedback. To address the donation aspect, I've added a note inside the README. Please take a look.

Forgive any confusion, and thanks for understanding. (added note regarding donations inside readme)
And please bear with me; English is not my native language.
