### ISSUE TITLE
Note how to discover document structure and class names

### ISSUE THREAD

**Issue by infogulch** [r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets#12]
I think it would be nice if the readme included a bit about how to discover css class names and the document structure. Basically:

> Note: You can discover all available class names and the document structure by opening the dev tools with `Ctrl+Shift+I` to browse the elements. See also [Build a theme](https://docs.obsidian.md/Themes/App+themes/Build+a+theme#Step+7+Discover+CSS+variables+in+use)

**Comment by r-u-s-h-i-k-e-s-h** [comment]
Hey, thanks for the suggestion!

I’ve added a new link in the "Additional Resources and Links" section that explains how to find CSS class names and the document structure using developer tools (`Ctrl+Shift+I`). You can check it out [here](https://forum.obsidian.md/t/obsidian-css-quick-guide/58178), or find it as the second link in that section [here](https://github.com/r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets?tab=readme-ov-file#-additional-resources-and-links).

**Comment by infogulch** [comment]
Great! 🙌
