### ISSUE TITLE
Kanban styling - Notion like Kanban board CSS still working with Kanban Plugin 2.0.51 in Obsidian 1.6.7?

### ISSUE THREAD

**Issue by wechsler42** [r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets#13]
Hi there,
thanks for providing this CSS snippet.
I tried to get it work in the combo Obsidian 1.6.7 , Default Theme and Kanban Plugin 2.0.51 . Unfortunately without luck . May I ask if this works for you or where I have to make some adjustments?
Thanks in advance for a hint.

**Comment by r-u-s-h-i-k-e-s-h** [comment]
It is working on my end
What is your Obsidian installer version?
![image](https://github.com/user-attachments/assets/84580686-1771-43d1-9380-3bf928896924)

**Comment by wechsler42** [comment]
Thanks for getting back to my issue. My installer version is 1.6.7 and my Obsidian version is also 1.6.7. I would like to work with this CSS snippet: Kanban styling - Notion like Kanban board.

**Comment by r-u-s-h-i-k-e-s-h** [comment]
Could you explain a bit more about the issue? It'll help me understand better since my English isn't that great

**Comment by wechsler42** [comment]
Hello again,
sure, I will try to explain it a bit better.
Setup: Obsidian installer version 1.6.7; Obsidian version:1.6.7. ; Kanban Plugin version 2.0.51; Obsidian default theme.

A: situation *without any* CSS snippet:
![image](https://github.com/user-attachments/assets/21088a08-d615-45d6-b6e0-e7440d9871b4)
B: situation with CSS snippet: [Kanban styling - Notion like Kanban board](https://github.com/r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets/blob/Collection/Snippets/Kanban%20styling%20-%20Notion%20like%20Kanban%20board.md)
![image](https://github.com/user-attachments/assets/f2a9080d-a7d8-45ad-93ac-f4d9fa5de15f)
C: situation with CSS snippet: [KanbanPlugin.css](https://github.com/spacewitches/Obsidian/blob/main/Minimal%20Theme/kanbanPlugin.css)
![image](https://github.com/user-attachments/assets/41cf672d-f3ba-49d5-9ae7-a4724c582a32)

So I think in B: there is colour missing in the lanes  and the whole Kanban board seems to be shrunk a bit. Does this have to look this way?

**Comment by r-u-s-h-i-k-e-s-h** [comment]
Thanks for explaining! I'm not that great with CSS, but I think if you remove everything below [this line](https://github.com/r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets/blob/d68947c13f0f3b7e11daf5c55e37af05c2faff0b/Snippets/Kanban%20styling%20-%20Notion%20like%20Kanban%20board.md?plain=1#L117) in the Notion-like Kanban board snippet, you should get the result you're after. 
If you run into more questions, you can ask on the [Obsidian discord server](https://discord.gg/obsidianmd). There are CSS wizards there who might be able to help you more!

**Comment by wechsler42** [comment]
Thanks for your help!
