### ISSUE TITLE
Infobox Callout Snippets breaks Layout

### ISSUE THREAD

**Issue by jettil** [r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets#4]
# Steps to Reproduce
1. Add Infobox Callout to Snippets folder
2. Activate Snippet
3. Check Files
4. Deactivate Snippet and delete it from Snippets folder
5. Check Files again

# Expected Behavior
* The only changes are to the infobox Callout
* After deactivating the snippet, the changes are reverted

# Actual Behavior
* Note Body is permanently moved right (or the title is moved left)
* Even after deinstalling the snipped, the error still shows
![image](https://github.com/r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets/assets/54105008/b4a93de1-e8c4-458e-9846-958c9f31047c)

**Comment by r-u-s-h-i-k-e-s-h** [comment]
Hey, sorry for the late reply. Could you try it again in the latest version? I can't seem to reproduce it
