### ISSUE TITLE
just thanks.

### ISSUE THREAD

**Issue by ksdavidc** [r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets#5]
Just wanted to say thank you for this compilation. Your name came up in a discord discussion with @sailKite, who sang your praises.

**Comment by r-u-s-h-i-k-e-s-h** [comment]
Hey, thank you for your kind words. I'm glad it's helpful. Big thanks to [**sailKite**](https://github.com/sailKiteV) though 😄. I mean, this wouldn't be possible without them!
